# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cancel_at_period_end',
            field=models.BooleanField(default='0'),
        ),
    ]
