# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160804_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cancel_at_period_end',
            field=models.BooleanField(default='False'),
        ),
    ]
