# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='subtitle', max_length=200),
            preserve_default=False,
        ),
    ]
